#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("aves.Droid.Resource", IsApplication=true)]

namespace aves.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int boton1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int equipoMenuPrinc = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int equipoOP1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int equipoOP2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int equipoOP3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int equipoOP4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int equipoOP5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int equipoOP6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int equipoOP7 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int equipoOP8 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int equipoOPCION = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int equipoOPCION2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int gaviota = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int habitOP2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int morfolOP2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int recomOP2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sonidoMenuPrinc = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int soniodOP2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tipoAveOP2 = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int equipoAgua = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int equipoBinoculares = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int equipoCamara = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int equipoLapiz = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int equipoLibreta = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int equipoLupa = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int equipoPinzas = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int equipoSanduche = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int imageButton1 = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int imageView1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int opcionEquipos = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int opcionHabitats = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int opcionMorfologia = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int opcionRecomendaciones = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int opcionSonidos = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int opcionTipoAves = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Equipos = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MenuPrincipal = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
